import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth";
import Auth from "@/app/components/Auth.jsx";
import Navbar from "./components/Navbar";

// import { usePathname } from "next/navigation";

//Everything in LAYOUT will be shown at all pages.
//Navbar, logout, banners, footer.

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gray-200">
          <AuthProvider>
            {/* allt i layout syns på ALLA sidor */}
            {/* {pathname === "/login" && <Auth />} */}
            <Navbar />
            <Auth />
            {children}
            {/* children är min page */}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
